### PR TITLE
Making Typescript options optional

### PR DESCRIPTION
**Pull request by drmikecrowe**

### CODE REVIEW

**Comment by taoqf** [comment]
Using `Partial`, we do not need `?` at all. so I will close this pr. If you have any question, please let me know.
Thanks for your work.

**Comment by drmikecrowe** [comment]
So, when I use version 3.1.3:


Error:
```
TS2740: Type '{ init: string; transitions: { name: string; from: string; to: string; }[]; 
      methods: { onBeforeTransition: (lifecycle: LifeCycle) => any; 
            onTransition: (lifecycle: LifeCycle) => any; 
            onLeaveState: (lifecycle: LifeCycle) => any; 
            onEnterState: (lifecycle: LifeCycle) => any; }; }' 
is missing the following properties from type 'Options': name, past, future, max, and 3 more.
```

Code:
```
export const fsmOptions: StateMachine.Options = {
    init: CLOSED_STATE,
    transitions: [
        { name: FIRE_DO_OPEN,                               from: CLOSED_STATE,                     to: OPENED_STATE,                        },
        { name: FIRE_DO_CLOSE,                              from: OPENED_STATE,                     to: CLOSED_STATE,                        },
    ],

    methods: {
        onBeforeTransition: function(lifecycle) {
            let trans = getTransNames(lifecycle.transition);
            if (!fsmDispatchFunctions.onBeforeTransition) return true;
            let event = "onBeforeTransition", 
                type = trans.beforeTransNameCaps;
            return fsmDispatchFunctions.onBeforeTransition({ event: event, type: type });
        },

        onTransition: function(lifecycle) {
            let trans = getTransNames(lifecycle.transition);
            if (!fsmDispatchFunctions.onTransition) return true;
            let event = "onTransition", 
                type = trans.transNameCaps;
            return fsmDispatchFunctions.onTransition({ event: event, type: type });
        },

        onLeaveState: function(lifecycle) {
            let from_state = getStateNames(lifecycle.from);
            if (!fsmDispatchFunctions.onLeaveState) return true;
            let event = "onLeaveState", 
                type = from_state.leaveStateNameCaps;
            return fsmDispatchFunctions.onLeaveState({ event: event, type: type });
        },

        onEnterState: function(lifecycle) {
            let to_state = getStateNames(lifecycle.to);
            if (!fsmDispatchFunctions.onEnterState) return true;
            let event = "onEnterState", 
                type = to_state.stateNameCaps;
            return fsmDispatchFunctions.onEnterState({ event: event, type: type });
        }
    }
};
```

How would you use `Partial` to address this?  Sorry if I'm missing something obvious

**Comment by taoqf** [comment]
Hmm, will

`export const fsmOptions: Partial<StateMachine.Options> = {`

 or 

```ts
export const fsmOptions = {
    init: CLOSED_STATE,
    transitions: [
        { name: FIRE_DO_OPEN,                               from: CLOSED_STATE,                     to: OPENED_STATE,                        },
        { name: FIRE_DO_CLOSE,                              from: OPENED_STATE,                     to: CLOSED_STATE,                        },
    ],

    methods: {
        onBeforeTransition: function(lifecycle) {
            let trans = getTransNames(lifecycle.transition);
            if (!fsmDispatchFunctions.onBeforeTransition) return true;
            let event = "onBeforeTransition", 
                type = trans.beforeTransNameCaps;
            return fsmDispatchFunctions.onBeforeTransition({ event: event, type: type });
        },

        onTransition: function(lifecycle) {
            let trans = getTransNames(lifecycle.transition);
            if (!fsmDispatchFunctions.onTransition) return true;
            let event = "onTransition", 
                type = trans.transNameCaps;
            return fsmDispatchFunctions.onTransition({ event: event, type: type });
        },

        onLeaveState: function(lifecycle) {
            let from_state = getStateNames(lifecycle.from);
            if (!fsmDispatchFunctions.onLeaveState) return true;
            let event = "onLeaveState", 
                type = from_state.leaveStateNameCaps;
            return fsmDispatchFunctions.onLeaveState({ event: event, type: type });
        },

        onEnterState: function(lifecycle) {
            let to_state = getStateNames(lifecycle.to);
            if (!fsmDispatchFunctions.onEnterState) return true;
            let event = "onEnterState", 
                type = to_state.stateNameCaps;
            return fsmDispatchFunctions.onEnterState({ event: event, type: type });
        }
    }
} as StateMachine.Options;
```

resolve your problem?

**Comment by drmikecrowe** [comment]
Ah, `Partial<StateMachine.Options>` did the trick.  Thanks, @taoqf

**Pull request closed without merging**
